---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: logger-clusterrole
  namespace: openshift-scanning
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
#- apiGroups:
#  - ""
#  resources:
#  - secrets
#  - services
#  verbs:
#  - create
#  - delete
#  - get
#  - list
#  - patch
#  - update
#  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
#- apiGroups:
#  - security.openshift.io
#  resources:
#  - securitycontextconstraints
#  verbs:
#  - create
#  - get
#  - update
#  - use
- apiGroups:
  - "config.openshift.io"
  resources:
  - clusterversions
  verbs:
  - get
  - list 
