apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logger-clusterrolebinding
  namespace: openshift-scanning
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logger-clusterrole
subjects:
- kind: ServiceAccount
  name: logger-sa
  namespace: openshift-scanning
