apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logger
  namespace: openshift-scanning
spec:
  selector:
    matchLabels:
      name: logger
  template:
    metadata:
      labels:
        name: logger
    spec:
      containers:
      - env:
        - name: OO_PAUSE_ON_START
          value: "false"
        - name: LOG_WRITER_URL
          value: http://logger.openshift-scanning.svc:8080/api/log
        - name: SCAN_LOG_FILE
          value: /host/var/log/openshift_managed_malware_scan.log
        - name: POD_LOG_FILE
          value: /host/var/log/openshift_managed_pod_creation.log
        - name: POD_SOCK
          value: "@rpc.pod.sock"
        - name: SCAN_SOCK
          value: "@rpc.scan.sock"
        - name: APP_SECRETS_PATH
          value: "/secrets/api_config.json"
        - name: SA_TOKEN_PATH
          value: "/var/run/secrets/kubernetes.io/serviceaccount/token"
        - name: OAPI_URL
          value: "https://openshift.default.svc.cluster.local"
        - name: CV_URL
          value: "/apis/config.openshift.io/v1/clusterversions"
        - name: MIDDLEWARE_LOGGER 
          value: "true"
        image: quay.io/app-sre/pod-logger@sha256:8c4d6118f4a475be29a9638198dffb96ad47d703e69e7750e8429a2e8e02a63d
        name: logger
        ports:
        - containerPort: 8080
          name: logger
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        volumeMounts:
        - mountPath: /secrets
          name: logger-secrets
      - env:
        - name: OO_PAUSE_ON_START
          value: "false"
        - name: SOCK
          value: "@rpc.pod.sock"
        image: quay.io/app-sre/log-printer@sha256:af480dffcf9953f37c97f81bcc5429d371685c3194c10368264dff0f12189426
        name: pod-printer
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      - env:
        - name: OO_PAUSE_ON_START
          value: "false"
        - name: SOCK
          value: "@rpc.scan.sock"
        image: quay.io/app-sre/log-printer@sha256:af480dffcf9953f37c97f81bcc5429d371685c3194c10368264dff0f12189426
        name: scan-printer
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      nodeSelector:
        node-role.kubernetes.io/master: ""
      serviceAccountName: logger-sa
      tolerations:
      - operator: Exists
      volumes:
      - name: logger-secrets
        secret:
          secretName: logger-secrets
