apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: loggerservice
    name: loggerservice
  name: loggerservice
  namespace: openshift-scanning
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: loggerservice
spec:
  ports:
  - name: loggerservice
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    name: logger
